version: '3.8'

services:
  mongo:
    image: mongo:6.0.5
    container_name: timesheet-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: timesheet-server
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongo:27017/timesheet?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: timesheet-client
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  mongo-data:
